### ISSUE TITLE
Points à voir

### ISSUE THREAD

**Issue by adr-miq** [Haldien/SAE_1-BomberBUT-Partie-1#2]
09/12/2024

- Quand le joueur essaie de se déplacer/poser une bombe sur une case invalide, le programme ne fait rien mais un tour passe quand même. Est-ce que c'est ce que l'on veut ?

- Dans fantomes.py : randint(0, 4) peut générer 5 valeurs différentes alors qu'il y a 4 directions.

**Comment by TeGuisho** [comment]
C'est réglé ^^
